name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # runs every midnight
  workflow_dispatch:     # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Pacman graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: Sanik0
          theme: pacman
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generate Pacman graph" || echo "No changes"
          git push
